### ISSUE TITLE
Better error handling while tests

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#804] opened 2018-03-01 12:03 UTC
Sometimes the tests fail because they found something wrong inside a doc but sometimes something else goes wrong which has different reasons.

In that case we have to filter only errors concerning the test so the test fails only then.

https://github.com/foundeo/cfdocs/blob/3f1d019101dabaf4ee9f9507f629db9bec9dc424/tests/tests/TestExamples.cfc#L31,L48

**Comment by pfreitag** [comment] 2018-03-01 15:28
Can you be more specific? 

I still want the test to fail if the example throws an exception. I agree there have been some engine bugs that have caused exceptions to happen when the code was infact valid -- but I have removed evaluate from the tests to avoid those. Are you aware of anything specific?

**Comment by shaedrich** [comment] 2018-03-01 15:31
I already wondered if something has been changed there^^

But it still fails/fails again: https://github.com/foundeo/cfdocs/pull/803#issuecomment-369554872

**Comment by pfreitag** [comment] 2018-03-01 15:45
It was just a temporary failure when running this code example:

`xmlValidate("https://www.w3schools.com/xml/note.xml", "https://www.w3schools.com/xml/note.xsd").status`

It couldn't connect to one of those URLs temporarily. This is the first time that has happened so I don't think it is necessary to write a special case for it -- if it keeps happening then I'd rather just change the test to point to a different url - if we make the test fail silently we won't know that it isn't being tested anymore.

**Comment by shaedrich** [comment] 2018-03-01 15:54
The test could succeed but we could better be notified by a log or something like this because the pr itself is valid.

**Comment by pfreitag** [comment] 2018-03-01 15:56
The problem is I don't look at the travis results unless they fail. So while the log might work it would not be noticed for a while.

**Comment by shaedrich** [comment] 2018-03-01 15:58
Hmmm... I see your point but it seems wrong to me. Do you have any other idea or should we simply leave it as it is.

**Comment by pfreitag** [comment] 2018-03-01 16:53
I'd say let's just leave it for now, there are bigger fish to fry... If it becomes a problem I'd say next step might be to add code to sleep then retry once if it fails.

I'll close this issue, but if it is a problem feel free to reopen it.

**Closed by pfreitag** 2018-03-01 16:53 UTC

**Comment by shaedrich** [comment] 2018-03-01 16:56
Nope, I'm fine with this.
